project:
  type: website
  output-dir: _site
  preview:
    port: 4200
    browser: true
    watch-inputs: true
    navigate: true
author:
- id: mjstowe
  name:
    given: MJ
    family: Stowe
    literal: MJ Stowe
  url: "{{< var homepage >}}"
  email: "{{< var email >}}"
  orcid: "{{< var orcid >}}"
  attributes:
    corresponding: true
  affiliations:
    - ref: kirby
    - ref: sanpud
website:
  repo-url: "https://github.com/mx-jx"
  repo-actions: [edit, issue]

  page-navigation: true
  bread-crumbs: false

  navbar:
    pinned: true
    background: "#E9DEFC"
    search: true
    left:
      # - text: "Experiment"
      #   file: notebook/survey-experiment.qmd
      # - text: "Methods & Models"
      #   file: notebook/marginal-means.qmd
      # - text: "Results"
      #   file: notebook/results.qmd
      - text: "Manuscript"
        file: notebook/manuscript.qmd

    right:
      - icon: github
        aria-label: github
        href: https://github.com/andrewheiss/silent-skywalk

  page-footer:
     left: |
       Content {{< fa brands creative-commons >}} 2024 by MJ Stowe<br>
       All content licensed under a {{< fa brands creative-commons >}}
       {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
       [Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/)
     right: |
       Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
       [View the source at {{< fa brands github >}} GitHub](https://github.com/mjxstowe)

format:
  html:
    # format options:
    theme: [cosmo, custom.scss]
    anchor-sections: true
    smooth-scroll: true
    html-math-method: katex
    email-obfuscation: none
    # table of contents:
    toc: true
    toc-depth: 3
    toc-location: right
    toc-title: "Contents"
    toc-expand: true
    # numbering:
    number-sections: false
    number-depth: 1
    # layout:
    cap-location: margin
    fig-cap-location: margin
    tbl-cap-location: margin
    page-layout: article
    title-block-style: default
    # code:
    code-fold: show
    code-summary: "Code"
    code-overflow: scroll
    code-line-numbers: true
    code-copy: true
    code-link: false
    code-annotations: true
    code-tools:
      source: "https://github.com/lnnrtwttkhn/quarto-article"
      toggle: true
      caption: "Code"
    highlight-style: monokai
    # execution:
    execute:
      eval: false
    # links:
    link-external-icon: false
    link-external-newwindow: true
    # references
    bibliography: references.bib
    csl: apa.csl
    citations-hover: true
    citation-location: document
    # language
    language: en
    # includes:
    include-after-body: plausible.html
    metadata-files:
      - _affiliations.yml
      - _variables.yml
    # metadata
    license: "CC BY"
    # rendering:
    from: "markdown+emoji"
    # website:
    search: false
    repo-actions: true
